name: Deploy to Artifact Registry

on:
  push:
    branches:
      - test

env:
  PROJECT_ID: engaged-hook-384215
  REGION: us-central1
  ARTIFACT_REGISTRY: us-central1-docker.pkg.dev
  SERVICE_ACCOUNT: test-sa@engaged-hook-384215.iam.gserviceaccount.com

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v0.3.0
        with:
          workload_identity_pool: "projects/591365510460/locations/global/workloadIdentityPools/example-pool/providers/example-gh-provider"
          workload_identity_service_account: ${{ env.SERVICE_ACCOUNT }}

      - name: Authenticate with Artifact Registry
        run: |
          gcloud auth configure-docker "${{ env.ARTIFACT_REGISTRY }}"
          
      - name: Build and push image to Artifact Registry
        run: |
          # Build your code here
          docker build -t ${{ env.ARTIFACT_REGISTRY }}/img:v1 .
          docker push ${{ env.ARTIFACT_REGISTRY }}/img:v1 .


# name: Set up Docker Build id: buildx uses: docker/setup-buildx-action@v2
# id: "auth"
# met "Authenticate to Google Cloud"
# Uses
# "google-github-actions/auth@vi"
# with:
# workload_suentity_provider: ${f env.WORKLOAD_IDENTITY_PROVIDER ½)
# service_account ( env. SERVICE_ACCOUNT ))
# - name: Auth docker run: |
# gcloud auth configure-docker europe-west2-docker.pkg.dev
# - name: Build and push id: docker_build uses: docker/build-push-actionav3 with:
# builder: ${{ steps.build.outputs. name })
# push: true
# tags: ${{ env. IMAGE })
# file: application/api/Dockerfile context: application/api build-args: |
# "VERSION=$({ env. TAG })"
# - name: Deploy run: |
# PROJECT_ID=$ (gcloud config get-value project)
# SUFFIX=S (echo "S{f env. TAG J" | tr ' .
# gcloud run deploy api \
# --revision-suffix=${SUFFIX} \
# --project=$(PROJECT_ID) \
# --set-env-vars=CP_PROJECT_ID=$(PROJECT_ID) |
# --image=${f env. IMAGE }} \
# -allow-unauthenticated \
# --region=europe-west2 \
# --ingress=all \
# --port=4000